# #####################################################################
# Automatically generated by qmake (2.01a) Mon Sep 3 15:23:45 2012
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp \
    ui/tabbeddocumentview.cpp \
    ui/linenumberarea.cpp \
    ui/codeeditor.cpp
HEADERS += ui/tabbeddocumentview.h \
    ui/codeeditor.h \
    ui/linenumberarea.h
FORMS += 
